# Generated by Django 3.0.8 on 2021-06-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LegalTech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=100)),
                ('payee_address', models.CharField(blank=True, max_length=500)),
                ('payer_name', models.CharField(blank=True, max_length=100)),
                ('payer_address', models.CharField(blank=True, max_length=500)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='LegalTech.Profile')),
            ],
        ),
    ]
